// <auto-generated />
namespace TrashPickupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditedTemporaryDatestartandenddateattributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedTemporaryDatestartandenddateattributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201610212115115_Edited TemporaryDate start and enddate attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
